name: documentation

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Download wowlua-ls
        uses: robinraju/release-downloader@v1
        with:
          repository: 'TradeSkillMaster/wowlua-ls'
          latest: true
          fileName: 'wowlua_ls-x86_64-unknown-linux-gnu'
          out-file-path: './'

      - name: Install wowlua_ls
        run: |
          chmod +x wowlua_ls-x86_64-unknown-linux-gnu
          mv wowlua_ls-x86_64-unknown-linux-gnu wowlua_ls
          echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH

      - uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install npm dependencies
        run: npm install
        working-directory: Docs

      - name: Build docs
        run: npm run docs:build
        working-directory: Docs

      - name: Upload artifact
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: Docs/.vitepress/dist/

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        id: deployment
        uses: actions/deploy-pages@v4
