name: PR Checks
on: [pull_request]
jobs:
  pr:
    name: Pull Request Checks
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
          path: LibTSMClass/

      - name: Install Lua 5.1.5
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1.5"

      - name: Download wowlua-ls
        uses: robinraju/release-downloader@v1
        with:
          repository: 'TradeSkillMaster/wowlua-ls'
          latest: true
          fileName: 'wowlua_ls-x86_64-unknown-linux-gnu'
          out-file-path: './'

      - name: Run wowlua-ls Check
        run: |
          chmod +x ./wowlua_ls-x86_64-unknown-linux-gnu
          ./wowlua_ls-x86_64-unknown-linux-gnu check LibTSMClass/

      - name: Run Unit Tests
        run: lua LibTSMClass/Tests/Unit/TestLibTSMClass.lua -o junit -n test-results.xml

      - name: Test Report
        uses: dorny/test-reporter@v3
        if: success() || failure()
        with:
          name: Unit Tests
          path: test-results.xml
          reporter: java-junit
